// Generated by gencpp from file yhs_can_msgs/front_velocity_free_ctrl_cmd.msg
// DO NOT EDIT!


#ifndef YHS_CAN_MSGS_MESSAGE_FRONT_VELOCITY_FREE_CTRL_CMD_H
#define YHS_CAN_MSGS_MESSAGE_FRONT_VELOCITY_FREE_CTRL_CMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yhs_can_msgs
{
template <class ContainerAllocator>
struct front_velocity_free_ctrl_cmd_
{
  typedef front_velocity_free_ctrl_cmd_<ContainerAllocator> Type;

  front_velocity_free_ctrl_cmd_()
    : ctrl_cmd_gear(0)
    , free_ctrl_cmd_velocity_lf(0.0)
    , free_ctrl_cmd_velocity_rf(0.0)  {
    }
  front_velocity_free_ctrl_cmd_(const ContainerAllocator& _alloc)
    : ctrl_cmd_gear(0)
    , free_ctrl_cmd_velocity_lf(0.0)
    , free_ctrl_cmd_velocity_rf(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _ctrl_cmd_gear_type;
  _ctrl_cmd_gear_type ctrl_cmd_gear;

   typedef float _free_ctrl_cmd_velocity_lf_type;
  _free_ctrl_cmd_velocity_lf_type free_ctrl_cmd_velocity_lf;

   typedef float _free_ctrl_cmd_velocity_rf_type;
  _free_ctrl_cmd_velocity_rf_type free_ctrl_cmd_velocity_rf;





  typedef boost::shared_ptr< ::yhs_can_msgs::front_velocity_free_ctrl_cmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yhs_can_msgs::front_velocity_free_ctrl_cmd_<ContainerAllocator> const> ConstPtr;

}; // struct front_velocity_free_ctrl_cmd_

typedef ::yhs_can_msgs::front_velocity_free_ctrl_cmd_<std::allocator<void> > front_velocity_free_ctrl_cmd;

typedef boost::shared_ptr< ::yhs_can_msgs::front_velocity_free_ctrl_cmd > front_velocity_free_ctrl_cmdPtr;
typedef boost::shared_ptr< ::yhs_can_msgs::front_velocity_free_ctrl_cmd const> front_velocity_free_ctrl_cmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yhs_can_msgs::front_velocity_free_ctrl_cmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yhs_can_msgs::front_velocity_free_ctrl_cmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yhs_can_msgs::front_velocity_free_ctrl_cmd_<ContainerAllocator1> & lhs, const ::yhs_can_msgs::front_velocity_free_ctrl_cmd_<ContainerAllocator2> & rhs)
{
  return lhs.ctrl_cmd_gear == rhs.ctrl_cmd_gear &&
    lhs.free_ctrl_cmd_velocity_lf == rhs.free_ctrl_cmd_velocity_lf &&
    lhs.free_ctrl_cmd_velocity_rf == rhs.free_ctrl_cmd_velocity_rf;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yhs_can_msgs::front_velocity_free_ctrl_cmd_<ContainerAllocator1> & lhs, const ::yhs_can_msgs::front_velocity_free_ctrl_cmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yhs_can_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yhs_can_msgs::front_velocity_free_ctrl_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yhs_can_msgs::front_velocity_free_ctrl_cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yhs_can_msgs::front_velocity_free_ctrl_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yhs_can_msgs::front_velocity_free_ctrl_cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yhs_can_msgs::front_velocity_free_ctrl_cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yhs_can_msgs::front_velocity_free_ctrl_cmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yhs_can_msgs::front_velocity_free_ctrl_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6ccb4ea5d60635b5d1a6ac7be60374c9";
  }

  static const char* value(const ::yhs_can_msgs::front_velocity_free_ctrl_cmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6ccb4ea5d60635b5ULL;
  static const uint64_t static_value2 = 0xd1a6ac7be60374c9ULL;
};

template<class ContainerAllocator>
struct DataType< ::yhs_can_msgs::front_velocity_free_ctrl_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yhs_can_msgs/front_velocity_free_ctrl_cmd";
  }

  static const char* value(const ::yhs_can_msgs::front_velocity_free_ctrl_cmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yhs_can_msgs::front_velocity_free_ctrl_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8    ctrl_cmd_gear\n"
"float32  free_ctrl_cmd_velocity_lf\n"
"float32  free_ctrl_cmd_velocity_rf\n"
;
  }

  static const char* value(const ::yhs_can_msgs::front_velocity_free_ctrl_cmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yhs_can_msgs::front_velocity_free_ctrl_cmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ctrl_cmd_gear);
      stream.next(m.free_ctrl_cmd_velocity_lf);
      stream.next(m.free_ctrl_cmd_velocity_rf);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct front_velocity_free_ctrl_cmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yhs_can_msgs::front_velocity_free_ctrl_cmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yhs_can_msgs::front_velocity_free_ctrl_cmd_<ContainerAllocator>& v)
  {
    s << indent << "ctrl_cmd_gear: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ctrl_cmd_gear);
    s << indent << "free_ctrl_cmd_velocity_lf: ";
    Printer<float>::stream(s, indent + "  ", v.free_ctrl_cmd_velocity_lf);
    s << indent << "free_ctrl_cmd_velocity_rf: ";
    Printer<float>::stream(s, indent + "  ", v.free_ctrl_cmd_velocity_rf);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YHS_CAN_MSGS_MESSAGE_FRONT_VELOCITY_FREE_CTRL_CMD_H
